const soundGrid=document.getElementById('sound-grid');
const detailContent=document.getElementById('detail-content');
const searchInput=document.getElementById('search-input');
const filterGroup=document.getElementById('filter-group');
const progressChip=document.getElementById('progress-chip');
const detailAudioBtn=document.getElementById('detail-audio-btn');
const listenCurrentBtn=document.getElementById('listen-current-btn');
const markLearnedBtn=document.getElementById('mark-learned-btn');
const resetProgressBtn=document.getElementById('reset-progress-btn');
const heroRandomBtn=document.getElementById('hero-random-btn');
const recordBtn=document.getElementById('record-btn');
const stopBtn=document.getElementById('stop-btn');
const recordedAudio=document.getElementById('recorded-audio');
const recordStatus=document.getElementById('record-status');
const quizBox=document.getElementById('quiz-box');
const quizScoreEl=document.getElementById('quiz-score');
const STORAGE_KEY='masterIpaLearned';
let currentFilter='all',currentSearch='',selectedSymbol=IPA_DATA[0]?.symbol||null;
let learnedSet=new Set(JSON.parse(localStorage.getItem(STORAGE_KEY)||'[]'));
let mediaRecorder=null,recordedChunks=[],quizScore=0,quizPool=[],currentQuiz=null;

function escapeHtml(text){return String(text).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#39;')}
function getFilteredData(){return IPA_DATA.filter(item=>{const matchesFilter=currentFilter==='all'||item.category===currentFilter;const q=currentSearch.trim().toLowerCase();const haystack=[item.symbol,item.keyword,item.category,item.label,item.ttsText,item.mouthTip,item.commonMistake,item.practice,...item.examples,...item.spellings,...item.pair].join(' ').toLowerCase();return matchesFilter&&(!q||haystack.includes(q))})}
function renderGrid(){const filtered=getFilteredData();if(!filtered.length){soundGrid.innerHTML='<div class="empty-state" style="grid-column:1/-1;min-height:200px"><div class="empty-icon">🐚</div><h3>No sounds found</h3><p>Try another search word or choose a different filter.</p></div>';return}if(!filtered.some(i=>i.symbol===selectedSymbol))selectedSymbol=filtered[0].symbol;soundGrid.innerHTML=filtered.map(item=>`<article class="sound-card ${item.symbol===selectedSymbol?'selected':''} ${learnedSet.has(item.symbol)?'learned':''}" data-symbol="${escapeHtml(item.symbol)}"><div class="sound-type">${escapeHtml(item.label)}</div><div class="sound-symbol">${escapeHtml(item.symbol)}</div><div class="sound-word">${escapeHtml(item.keyword)}</div><div class="sound-spelling"><strong>Spelling:</strong> ${escapeHtml(item.spellings.join(', '))}</div><div class="card-actions"><button class="small-btn" type="button" data-action="study" data-symbol="${escapeHtml(item.symbol)}">Study</button><button class="round-btn" type="button" data-action="play" data-symbol="${escapeHtml(item.symbol)}" title="Play audio">🔊</button></div></article>`).join('')}
function renderDetail(){const item=IPA_DATA.find(s=>s.symbol===selectedSymbol);if(!item){detailContent.innerHTML='<div class="empty-state"><div class="empty-icon">🐬</div><h3>Choose a sound card</h3></div>';return}detailContent.innerHTML=`<div class="sound-hero"><div class="sound-badge">${escapeHtml(item.symbol)}</div><div class="sound-meta"><h3>${escapeHtml(item.symbol)} • ${escapeHtml(item.keyword)}</h3><p class="keyword">Main keyword: ${escapeHtml(item.keyword)}</p><div class="tag-row"><span class="tag">${escapeHtml(item.label)}</span><span class="tag">Pair: ${escapeHtml(item.pair.join(' ↔ '))}</span></div></div></div><div class="info-grid"><div class="info-card"><h4>👄 Mouth tip</h4><p>${escapeHtml(item.mouthTip)}</p></div><div class="info-card"><h4>⚠️ Common mistake</h4><p>${escapeHtml(item.commonMistake)}</p></div><div class="info-card"><h4>🔤 Common spellings</h4><ul>${item.spellings.map(x=>`<li>${escapeHtml(x)}</li>`).join('')}</ul></div><div class="info-card"><h4>📚 Example words</h4><ul>${item.examples.map(x=>`<li>${escapeHtml(x)}</li>`).join('')}</ul></div><div class="info-card full"><h4>🗣️ Shadowing sentence</h4><p>${escapeHtml(item.practice)}</p></div><div class="info-card full"><h4>🎧 Audio hint</h4><p>${escapeHtml(item.ttsText)}</p></div></div>`}
function updateProgress(){progressChip.textContent=`${learnedSet.size} / ${IPA_DATA.length} learned`}
function saveProgress(){localStorage.setItem(STORAGE_KEY,JSON.stringify([...learnedSet]));updateProgress();renderGrid()}
function speak(text,rate=.82){if(!('speechSynthesis'in window)){alert('Speech synthesis is not supported in this browser.');return}speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='en-GB';u.rate=rate;u.pitch=1.05;const voices=speechSynthesis.getVoices();u.voice=voices.find(v=>/en-GB|English.*UK/i.test(v.lang+' '+v.name))||voices.find(v=>/en-US|English/i.test(v.lang+' '+v.name))||null;speechSynthesis.speak(u)}
function playSound(symbol){const item=IPA_DATA.find(s=>s.symbol===symbol);if(!item)return;selectedSymbol=item.symbol;renderGrid();renderDetail();speak(`${item.ttsText} Example words: ${item.examples.join(', ')}. Repeat: ${item.practice}`)}
function chooseSound(symbol){selectedSymbol=symbol;renderGrid();renderDetail()}
function getSelectedItem(){return IPA_DATA.find(i=>i.symbol===selectedSymbol)||null}
function initRecording(){if(!navigator.mediaDevices?.getUserMedia){recordStatus.textContent='Your browser does not support microphone recording.';recordBtn.disabled=true;return}recordBtn.addEventListener('click',async()=>{try{const stream=await navigator.mediaDevices.getUserMedia({audio:true});mediaRecorder=new MediaRecorder(stream);recordedChunks=[];mediaRecorder.addEventListener('dataavailable',e=>{if(e.data.size)recordedChunks.push(e.data)});mediaRecorder.addEventListener('stop',()=>{const blob=new Blob(recordedChunks,{type:'audio/webm'});recordedAudio.src=URL.createObjectURL(blob);recordStatus.textContent='Recording complete. Listen to your voice below.';stream.getTracks().forEach(t=>t.stop())});mediaRecorder.start();recordStatus.textContent='Recording... pronounce the selected sound and sentence.';recordBtn.disabled=true;stopBtn.disabled=false}catch(e){recordStatus.textContent='Microphone permission was denied or not available.'}});stopBtn.addEventListener('click',()=>{if(mediaRecorder&&mediaRecorder.state!=='inactive'){mediaRecorder.stop();recordBtn.disabled=false;stopBtn.disabled=true}})}
function shuffle(a){const c=[...a];for(let i=c.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[c[i],c[j]]=[c[j],c[i]]}return c}
function buildQuizPool(){quizPool=shuffle(IPA_DATA.filter(i=>i.pair?.length===2)).slice(0,10).map(item=>{const wrong=item.pair.find(p=>p!==item.symbol)||item.pair[1];return{prompt:`Which sound do you hear in the word "${item.keyword}"?`,listenText:`${item.ttsText} ${item.keyword}`,word:item.keyword,correct:item.symbol,options:shuffle([item.symbol,wrong])}})}
function renderQuizStart(){quizBox.innerHTML='<p class="quiz-intro">Press start to practice listening and distinguishing similar sounds.</p><button id="start-quiz-btn" class="btn primary" type="button">Start quiz</button>';document.getElementById('start-quiz-btn').addEventListener('click',startQuiz)}
function renderQuizQuestion(){if(!quizPool.length){quizBox.innerHTML=`<h3>🎉 Quiz finished!</h3><p class="quiz-intro">Great job. Your final score is <strong>${quizScore}</strong>.</p><button id="restart-quiz-btn" class="btn primary" type="button">Play again</button>`;document.getElementById('restart-quiz-btn').addEventListener('click',startQuiz);return}currentQuiz=quizPool.shift();quizBox.innerHTML=`<p class="quiz-intro">${escapeHtml(currentQuiz.prompt)}</p><div class="question-word">${escapeHtml(currentQuiz.word)}</div><div class="record-actions"><button id="quiz-audio-btn" class="btn secondary" type="button">🔊 Play word</button></div><div class="option-grid">${currentQuiz.options.map(o=>`<button class="option-btn" data-option="${escapeHtml(o)}" type="button">${escapeHtml(o)}</button>`).join('')}</div><p id="quiz-feedback" class="mini-note">Choose the correct IPA sound.</p>`;document.getElementById('quiz-audio-btn').addEventListener('click',()=>speak(currentQuiz.listenText));quizBox.querySelectorAll('.option-btn').forEach(btn=>btn.addEventListener('click',()=>handleQuizAnswer(btn.dataset.option,btn)))}
function handleQuizAnswer(option,clicked){const buttons=[...quizBox.querySelectorAll('.option-btn')];buttons.forEach(b=>b.disabled=true);const feedback=document.getElementById('quiz-feedback');buttons.forEach(b=>{if(b.dataset.option===currentQuiz.correct)b.classList.add('correct');else if(b===clicked)b.classList.add('wrong')});if(option===currentQuiz.correct){quizScore++;feedback.textContent='Correct! Nice listening.'}else feedback.textContent=`Not quite. The correct sound is ${currentQuiz.correct}.`;quizScoreEl.textContent=`Score: ${quizScore}`;const n=document.createElement('button');n.className='btn primary';n.type='button';n.textContent=quizPool.length?'Next question':'See result';n.addEventListener('click',renderQuizQuestion);quizBox.appendChild(n)}
function startQuiz(){quizScore=0;quizScoreEl.textContent='Score: 0';buildQuizPool();renderQuizQuestion()}
function bindEvents(){searchInput.addEventListener('input',e=>{currentSearch=e.target.value;renderGrid()});filterGroup.addEventListener('click',e=>{const b=e.target.closest('.filter-btn');if(!b)return;currentFilter=b.dataset.filter;filterGroup.querySelectorAll('.filter-btn').forEach(x=>x.classList.toggle('active',x===b));renderGrid()});soundGrid.addEventListener('click',e=>{const a=e.target.closest('[data-action]');if(a){a.dataset.action==='play'?playSound(a.dataset.symbol):chooseSound(a.dataset.symbol);return}const card=e.target.closest('.sound-card');if(card)chooseSound(card.dataset.symbol)});detailAudioBtn.addEventListener('click',()=>{const i=getSelectedItem();if(i)playSound(i.symbol)});listenCurrentBtn.addEventListener('click',()=>{const i=getSelectedItem();if(i)playSound(i.symbol)});markLearnedBtn.addEventListener('click',()=>{const i=getSelectedItem();if(i){learnedSet.add(i.symbol);saveProgress()}});resetProgressBtn.addEventListener('click',()=>{if(confirm('Reset all learned sound progress?')){learnedSet=new Set;saveProgress()}});heroRandomBtn.addEventListener('click',()=>{const i=IPA_DATA[Math.floor(Math.random()*IPA_DATA.length)];chooseSound(i.symbol);playSound(i.symbol);location.hash='#library'})}
function init(){renderGrid();renderDetail();updateProgress();bindEvents();initRecording();renderQuizStart();if('speechSynthesis'in window)speechSynthesis.onvoiceschanged=()=>{}}
init();