// Vietnamese explanations layered on top of the original IPA dataset.
// IPA symbols, English keywords, examples, spellings and shadowing sentences stay in English.
const IPA_VI = {
'/iː/':{ttsText:'Âm /iː/ dài, như trong từ “sheep”.',mouthTip:'Kéo nhẹ hai khóe miệng sang hai bên, lưỡi nâng cao về phía trước và giữ âm dài hơn.',commonMistake:'Không đọc quá ngắn thành /ɪ/. Hãy chú ý độ dài của nguyên âm.'},
'/ɪ/':{ttsText:'Âm /ɪ/ ngắn, như trong từ “ship”.',mouthTip:'Thả lỏng môi và hàm; lưỡi nâng khá cao nhưng thấp hơn /iː/. Âm phải ngắn và nhẹ.',commonMistake:'Không kéo dài thành /iː/. Đây là lỗi rất thường gặp khi phân biệt ship – sheep.'},
'/e/':{ttsText:'Âm /e/, như trong từ “bed”.',mouthTip:'Mở miệng vừa phải, hàm thả lỏng, phần trước của lưỡi hơi nâng lên.',commonMistake:'Không mở miệng quá rộng để biến thành /æ/.'},
'/æ/':{ttsText:'Âm /æ/, như trong từ “cat”.',mouthTip:'Hạ hàm rõ hơn, mở miệng rộng và để lưỡi thấp ở phía trước.',commonMistake:'Không đọc quá khép thành /e/. Cần mở miệng rộng hơn khi phát âm.'},
'/ʌ/':{ttsText:'Âm /ʌ/ ngắn, như trong từ “cup”.',mouthTip:'Giữ môi trung tính, lưỡi ở vị trí trung tâm và phát âm ngắn, gọn.',commonMistake:'Không tròn môi như /ɒ/ và không kéo dài âm.'},
'/ɑː/':{ttsText:'Âm /ɑː/ dài, như trong từ “car”.',mouthTip:'Mở miệng khá rộng, lưỡi hạ thấp và kéo âm dài.',commonMistake:'Không đọc quá ngắn. Hãy cảm nhận rõ độ dài của âm /ɑː/.'},
'/ɒ/':{ttsText:'Âm /ɒ/ ngắn, như trong từ “hot”.',mouthTip:'Mở miệng vừa phải, môi hơi tròn, lưỡi thấp và lùi về sau.',commonMistake:'Không kéo dài thành /ɔː/.'},
'/ɔː/':{ttsText:'Âm /ɔː/ dài, như trong từ “law”.',mouthTip:'Môi tròn rõ hơn, lưỡi lùi về sau và giữ âm dài.',commonMistake:'Không rút ngắn thành /ɒ/. Chú ý độ dài và độ tròn của môi.'},
'/ʊ/':{ttsText:'Âm /ʊ/ ngắn, như trong từ “book”.',mouthTip:'Môi hơi tròn, lưỡi nâng về phía sau nhưng giữ cơ miệng tương đối thả lỏng.',commonMistake:'Không kéo dài và căng thành /uː/.'},
'/uː/':{ttsText:'Âm /uː/ dài, như trong từ “blue”.',mouthTip:'Tròn môi rõ, lưỡi nâng cao về phía sau và giữ âm dài.',commonMistake:'Không đọc quá ngắn hoặc quá lỏng như /ʊ/.'},
'/ɜː/':{ttsText:'Âm /ɜː/ dài, như trong từ “bird”.',mouthTip:'Giữ môi trung tính, lưỡi ở giữa khoang miệng và kéo âm dài.',commonMistake:'Trong kiểu Anh-Anh, không thêm âm /r/ mạnh ở cuối.'},
'/ə/':{ttsText:'Âm schwa /ə/, như âm đầu trong “about”.',mouthTip:'Đây là nguyên âm yếu nhất. Thả lỏng hoàn toàn miệng và phát âm rất nhẹ, rất ngắn.',commonMistake:'Không nhấn mạnh schwa như một nguyên âm đầy đủ.'},
'/eɪ/':{ttsText:'Nguyên âm đôi /eɪ/, như trong từ “day”.',mouthTip:'Bắt đầu gần /e/ rồi trượt dần lên vị trí của /ɪ/.',commonMistake:'Không giữ nguyên một âm /e/ phẳng; cần có chuyển động của lưỡi.'},
'/aɪ/':{ttsText:'Nguyên âm đôi /aɪ/, như trong từ “my”.',mouthTip:'Bắt đầu với miệng mở và lưỡi thấp, sau đó trượt lên gần /ɪ/.',commonMistake:'Không bỏ mất phần trượt ở cuối âm.'},
'/ɔɪ/':{ttsText:'Nguyên âm đôi /ɔɪ/, như trong từ “boy”.',mouthTip:'Bắt đầu với môi tròn ở /ɔ/ rồi chuyển nhanh về /ɪ/.',commonMistake:'Không đọc thành một âm /ɔː/ kéo dài.'},
'/aʊ/':{ttsText:'Nguyên âm đôi /aʊ/, như trong từ “now”.',mouthTip:'Bắt đầu với miệng mở, sau đó thu môi dần về vị trí tròn của /ʊ/.',commonMistake:'Không đọc quá nhanh khiến mất phần chuyển âm.'},
'/əʊ/':{ttsText:'Nguyên âm đôi /əʊ/, như trong từ “go”.',mouthTip:'Bắt đầu ở vị trí trung tâm, sau đó môi tròn dần về phía /ʊ/.',commonMistake:'Không biến thành /ɔː/; cần nghe rõ chuyển động của nguyên âm đôi.'},
'/ɪə/':{ttsText:'Nguyên âm đôi /ɪə/, như trong từ “ear”.',mouthTip:'Bắt đầu từ /ɪ/ rồi thả lỏng dần về schwa /ə/.',commonMistake:'Không nhấn quá mạnh phần /ə/ ở cuối.'},
'/eə/':{ttsText:'Nguyên âm đôi /eə/, như trong từ “hair”.',mouthTip:'Bắt đầu từ /e/, sau đó lưỡi di chuyển về vị trí trung tâm /ə/.',commonMistake:'Không đọc thành một âm /e/ đơn.'},
'/ʊə/':{ttsText:'Nguyên âm đôi /ʊə/, như trong từ “tour”.',mouthTip:'Bắt đầu với môi tròn ở /ʊ/, sau đó thả lỏng về schwa /ə/.',commonMistake:'Âm này thay đổi theo giọng địa phương; khi luyện hãy giữ hai phần chuyển âm rõ ràng.'},
'/p/':{ttsText:'Phụ âm /p/, như trong từ “pen”.',mouthTip:'Khép hai môi, giữ hơi phía sau rồi bật môi ra để tạo luồng hơi rõ. Không rung dây thanh.',commonMistake:'Cần bật hơi rõ, đặc biệt khi /p/ đứng đầu từ.'},
'/b/':{ttsText:'Phụ âm /b/, như trong từ “book”.',mouthTip:'Khép hai môi giống /p/ nhưng bật âm có rung dây thanh.',commonMistake:'Không đọc mất độ rung để biến thành /p/.'},
'/t/':{ttsText:'Phụ âm /t/, như trong từ “tea”.',mouthTip:'Đặt đầu lưỡi ngay sau răng trên, chặn hơi rồi bật ra nhanh. Không rung dây thanh.',commonMistake:'Tránh thêm nguyên âm “ơ” sau /t/, đặc biệt ở cuối từ.'},
'/d/':{ttsText:'Phụ âm /d/, như trong từ “dog”.',mouthTip:'Vị trí lưỡi giống /t/ nhưng có rung dây thanh khi bật âm.',commonMistake:'Không làm mất độ rung khiến /d/ nghe giống /t/.'},
'/k/':{ttsText:'Phụ âm /k/, như trong từ “cat”.',mouthTip:'Nâng phần sau của lưỡi chạm ngạc mềm, giữ hơi rồi bật ra. Không rung dây thanh.',commonMistake:'Không thêm nguyên âm sau /k/ khi âm này ở cuối từ.'},
'/g/':{ttsText:'Phụ âm /g/, như trong từ “go”.',mouthTip:'Vị trí lưỡi giống /k/ nhưng có rung dây thanh.',commonMistake:'Giữ độ rung rõ; không làm âm quá nhẹ hoặc biến thành /k/.'},
'/f/':{ttsText:'Phụ âm /f/, như trong từ “fish”.',mouthTip:'Chạm nhẹ răng trên vào môi dưới và đẩy hơi qua khe hẹp. Không rung dây thanh.',commonMistake:'Không khép cả hai môi như khi phát âm /p/.'},
'/v/':{ttsText:'Phụ âm /v/, như trong từ “van”.',mouthTip:'Giữ răng trên chạm môi dưới như /f/ nhưng thêm rung dây thanh.',commonMistake:'Không đọc /v/ thành /w/ hoặc /f/.'},
'/θ/':{ttsText:'Âm /θ/ vô thanh, như trong từ “think”.',mouthTip:'Đặt đầu lưỡi nhẹ giữa hai hàm răng và thổi hơi ra. Không rung dây thanh.',commonMistake:'Không thay bằng /t/ hoặc /s/. Hãy để đầu lưỡi thực sự lộ nhẹ giữa hai răng.'},
'/ð/':{ttsText:'Âm /ð/ hữu thanh, như trong từ “this”.',mouthTip:'Vị trí lưỡi giống /θ/ nhưng có rung dây thanh.',commonMistake:'Không thay bằng /d/. Cần duy trì luồng hơi giữa răng.'},
'/s/':{ttsText:'Phụ âm /s/, như trong từ “sun”.',mouthTip:'Đưa lưỡi gần lợi trên nhưng không chạm, tạo luồng hơi rít qua khe hẹp. Không rung dây thanh.',commonMistake:'Không bật giọng thành /z/.'},
'/z/':{ttsText:'Phụ âm /z/, như trong từ “zoo”.',mouthTip:'Vị trí miệng giống /s/ nhưng có rung dây thanh.',commonMistake:'Phải giữ độ rung rõ, đặc biệt ở cuối từ.'},
'/ʃ/':{ttsText:'Phụ âm /ʃ/, như trong từ “she”.',mouthTip:'Môi hơi đưa ra trước, lưỡi nâng về phía sau lợi và để hơi thoát đều.',commonMistake:'Không đọc thành /s/. Âm /ʃ/ cần môi tròn và vị trí lưỡi lùi hơn.'},
'/ʒ/':{ttsText:'Phụ âm /ʒ/, như trong từ “measure”.',mouthTip:'Giữ vị trí giống /ʃ/ nhưng thêm rung dây thanh.',commonMistake:'Không thay bằng /z/ hoặc /ʃ/.'},
'/h/':{ttsText:'Phụ âm /h/, như trong từ “hat”.',mouthTip:'Thở hơi nhẹ qua thanh môn; miệng chuẩn bị theo nguyên âm đứng ngay sau.',commonMistake:'Không bỏ mất /h/ ở đầu những từ cần phát âm âm này.'},
'/m/':{ttsText:'Phụ âm mũi /m/, như trong từ “moon”.',mouthTip:'Khép kín hai môi, rung dây thanh và để hơi thoát qua mũi.',commonMistake:'Hai môi phải khép hoàn toàn; không để âm chuyển thành /n/.'},
'/n/':{ttsText:'Phụ âm mũi /n/, như trong từ “nose”.',mouthTip:'Đầu lưỡi chạm ngay sau răng trên, rung dây thanh và để hơi thoát qua mũi.',commonMistake:'Không kéo vị trí lưỡi quá sâu về phía sau như /ŋ/.'},
'/ŋ/':{ttsText:'Phụ âm mũi /ŋ/, như trong từ “sing”.',mouthTip:'Nâng phần sau của lưỡi chạm ngạc mềm và để hơi thoát qua mũi.',commonMistake:'Không tự động thêm /g/ ở cuối “sing”, “long”… nếu từ đó không phát âm /g/.'},
'/l/':{ttsText:'Phụ âm /l/, như trong từ “light”.',mouthTip:'Đầu lưỡi chạm vùng ngay sau răng trên, để hơi thoát qua hai bên lưỡi.',commonMistake:'Không thay /l/ bằng /n/ và không cuộn lưỡi quá mạnh.'},
'/r/':{ttsText:'Phụ âm /r/, như trong từ “red”.',mouthTip:'Kéo lưỡi hơi lùi về sau nhưng không chạm vòm miệng; môi có thể hơi tròn.',commonMistake:'Không rung đầu lưỡi mạnh như âm “r” tiếng Việt.'},
'/j/':{ttsText:'Phụ âm /j/, như âm “y” trong “yes”.',mouthTip:'Nâng phần trước của lưỡi gần vòm miệng rồi trượt nhanh sang nguyên âm tiếp theo.',commonMistake:'Không kéo dài thành một nguyên âm hoàn chỉnh.'},
'/w/':{ttsText:'Phụ âm /w/, như trong từ “wet”.',mouthTip:'Tròn môi rõ rồi nhanh chóng chuyển sang nguyên âm tiếp theo; phần sau của lưỡi hơi nâng.',commonMistake:'Không đọc /w/ thành /v/.'},
'/tʃ/':{ttsText:'Phụ âm /tʃ/, như trong từ “chair”.',mouthTip:'Bắt đầu bằng vị trí /t/, giữ hơi rất ngắn rồi giải phóng trực tiếp thành /ʃ/.',commonMistake:'Không tách thành hai âm rời; cần tạo một âm bật-xát liền mạch.'},
'/dʒ/':{ttsText:'Phụ âm /dʒ/, như trong từ “juice”.',mouthTip:'Bắt đầu bằng vị trí /d/ rồi giải phóng trực tiếp thành /ʒ/, đồng thời giữ rung dây thanh.',commonMistake:'Không đọc thành /z/ hoặc tách thành hai âm riêng.'}
};
IPA_DATA.forEach(item=>{const vi=IPA_VI[item.symbol];if(vi)Object.assign(item,vi)});
